### ISSUE TITLE
Use Pi Hole Docker?

### ISSUE THREAD

**Issue by gurabli** [qdm12/cloudflare-dns-server#10]
Hi,
I'm about to configure my Pi Hole, but on my home server and in container. First I wanted to use CF container with DNS over HTTPS, but I realized I saw your container. 
I don't mind to use TLS instead of HTTPS, as I ser the only downside of TLS is that ISP can see that there are encrypted DNS requists sent from me. They can't see what and where. 

Anyway, did you ever tried to configure this container with Pi Hole container? I saw some guides how to do this, I can post them if you are interested.

**Comment by qdm12** [comment]
Hi gurabli,

I think you would just have to point the DNS servers IP in Pihole to the DoT cloudflare container IP (or `127.0.0.1` if port 53 is published). I am about to set up PiHole for my home as well.. except my ISP cut my Internet off recently so I'll probably have to wait a few days :smile:

**Comment by gurabli** [comment]
It is not so easy, as it involves two containers and the router too.
I'll post some links later. And maybe Cloudflared container is also a good idea to look into. 
Will be nice to check this out together!

**Comment by qdm12** [comment]
Hi there,

I'm having the same problem today 😄 
For Pihole, I would suggest to run it as a container in the same network as this container, and set PiHole's env variable `DNS1` to the LAN IP address of the cloudflare-dns-server container. I'm about to test it out! Let me know if you have tried it or something similar.

Thanks !

**Comment by qdm12** [comment]
Yep works for me (at least the DNS part, did not do the DHCP part yet):

My PiHole docker-compose.yml:

```yml
version: '3.7'
services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    environment:
      - TZ=Canada/Eastern
      - WEBPASSWORD=<password>
      - DNS1=10.0.0.2
    volumes:
       - ./pihole:/etc/pihole
       - ./dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 10.0.0.2
    networks:
      mynet:
        ipv4_address: 10.0.0.3
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 443:443/tcp
    expose: # I use a proxy
      - 80/tcp
    restart: always

networks:
  mynet:
    external: true
```

where the cloudflare DNS server container runs also in `mynet` with IP address `10.0.0.2`. I will check more tomorrow about all the features correctly but it seems to work so far, running a dnsleaktest.com gives me only Cloudflare DNS servers 😄
