### ISSUE TITLE
Health checking is KO

### ISSUE THREAD

**Issue by comassky** [qdm12/cloudflare-dns-server#23]
Hi all,

Very awesome work ! Thanks ;)

I noticed that the container could not go to healthy => remains on starting
`
72bd9443b31f        qmcgaw/cloudflare-dns-server   "/bin/sh -c /unbound…"   4 minutes ago       Up 4 minutes (health: starting)                                                        Dns`

Ping of duckduckgo inside container is KO

![image](https://user-images.githubusercontent.com/48486646/72370782-3a412980-3703-11ea-8792-8f73aea00b9e.png)

The dns works very well

```
$ dig @localhost duckduckgo.com

; <<>> DiG 9.11.5-P4-5.1-Debian <<>> @localhost duckduckgo.com
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3738
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;duckduckgo.com.                        IN      A

;; ANSWER SECTION:
duckduckgo.com.         3532    IN      A       46.51.179.90
duckduckgo.com.         3532    IN      A       79.125.105.113
duckduckgo.com.         3532    IN      A       176.34.155.23

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: mar. janv. 14 19:23:02 CET 2020
;; MSG SIZE  rcvd: 91
```

This is my docker-compose

```yml
cloudflare-dns-server:
   environment:
     - VERBOSITY=1
     - VERBOSITY_DETAILS=0
     - PROVIDERS=cloudflare,quad9
     - BLOCK_NSA=on
  image: qmcgaw/cloudflare-dns-server
  container_name: Dns
  network_mode: host
```
