### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by woiza** [qdm12/cloudflare-dns-server#26]
I use docker compose on a arm64 server and get the following error:

~/container-conf/tls-dns-server$ docker-compose up
Building cloudflare-dns-tls
ERROR: Cannot locate specified Dockerfile: Dockerfile

Here is my compose file:

```
version: "3.7"
services:
  cloudflare-dns-tls:
    build: .
    image: qmcgaw/cloudflare-dns-server
    container_name: cloudflare-dns-tls
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=1
      - BLOCK_MALICIOUS=off
      - BLOCK_NSA=off
      - BLOCK_SURVEILLANCE=off
      - BLOCK_ADS=off
      - CACHING=off
      - PROVIDER=google,quad9
    ports:
      - 53:53/udp
    network_mode: bridge
    restart: unless-stopped
```

What am I missing?
