### ISSUE TITLE
UNBLOCK environment variable isn't working

### ISSUE THREAD

**Issue by JayNewstrom** [qdm12/cloudflare-dns-server#30]
Here's my docker compose file:

```
version: '3.1'

services:
  cloudflare-dns-server:
    image: qmcgaw/cloudflare-dns-server
    restart: always
    volumes:
      - ./unbound/include.conf:/unbound/include.conf:ro
    environment:
      - BLOCK_MALICIOUS=off
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
      - PRIVATE_ADDRESS=192.168.1.0/24
      - UNBLOCK=maven.fabric.io
    ports:
      - 53:53/udp
```

When I run `dig maven.fabric.io` without blocking surveillance and ads it returns the  IP. Example:
```
$ dig maven.fabric.io

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> maven.fabric.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 30856
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;maven.fabric.io.               IN      A

;; ANSWER SECTION:
maven.fabric.io.        3600    IN      A       13.226.16.232

;; Query time: 338 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Mar 11 11:55:44 CDT 2020
;; MSG SIZE  rcvd: 60
```
When I run with the docker compose above, I get nothing back. Example:
```
$ dig maven.fabric.io

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> maven.fabric.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 24691
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;maven.fabric.io.               IN      A

;; Query time: 0 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Wed Mar 11 11:54:43 CDT 2020
;; MSG SIZE  rcvd: 44
```
